### set key value
POST http://localhost:8080/set
Content-Type: application/json

{
  "key": "hello",
  "value": "world"
}

### get key
GET http://localhost:8080/get?key=hello

### mset key value key value
POST http://localhost:8080/multi-set
Content-Type: application/json

[
  {
    "key": "hello",
    "value": "world"
  },
  {
    "key": "hi",
    "value": "hello"
  }
]

### mget key [key...]
GET http://localhost:8080/multi-get?key=hello&key=hidas

